### ISSUE TITLE
Welcome to Node-React-MySQL Discussions!

### ISSUE THREAD

**Issue by encourage317125** [sbsoso0411/Node-React-MySQL#2]
How can I write node running scripts on Ubuntu?
It works fine for windows, but if I try on Ubuntu, it fails and shows error.

**Comment by sbsoso0411** [comment]
You must use export on Ubuntu instaed of SET on Windows.
And also should care about some white spaces.

Here are the examples.

"mobile-windows": "SET NODE_SVIL=mobile&SET NODE_ENV=development&nodemon app.js",
"mobile-ubuntu": "export NODE_SVIL=mobile && export NODE_ENV=development && nodemon app.js",
